name: morphosis_flutter_demo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #  ==================  Core  ==================

  # A powerful Http client for Dart, which supports Interceptors,
  # FormData, Request Cancellation, File Downloading, Timeout etc.
  dio: ^4.0.0

  # Flutter plugin for reading and writing simple key-value pairs.
  # Wraps NSUserDefaults on iOS and SharedPreferences on Android.
  shared_preferences: ^2.0.6


  flutter_bloc: ^7.0.1


  # Simple direct Service Locator that allows to decouple the interface from a concrete
  # implementation and to access the concrete implementation from everywhere in your App"
  get_it: ^7.1.3
  get: ^4.1.4

  # Plugin for error catching. Allows handling errors when they're not catched by developer.
  # Plugin provides multiple handlers for errors.
  catcher: ^0.6.6

  #  ==================  UI  ==================

  # Default icons asset for Cupertino widgets based on Apple styled icons
  cupertino_icons: ^1.0.3

  # A collection of loading indicators animated with flutter.
  flutter_spinkit: ^5.0.0

  # A package to include fonts from fonts.google.com in your Flutter app.
  google_fonts: ^2.1.0

  # Flutter library to load and cache network images.
  # Can also be used with placeholder and error widgets.
  cached_network_image: ^3.0.0

  # A carousel slider widget, support infinite scroll and custom child widget
  carousel_slider: ^4.0.0

  # swiper/carousel for flutter, with multiple layouts,
  # infinite loop. Compatible with Android & iOS.
  card_swiper: ^1.0.2


  fl_chart: ^0.36.2


  #  ==================  UTILS  ==================

  # Provides APIs for debugging and error logging.
  # This library introduces abstractions similar to those used in other languages,
  # such as the Closure JS Logger and java.util.logging.Logger.
  logging: ^1.0.1


  # Toast Library for Flutter, Easily create toast messages in single line of code
  fluttertoast: ^8.0.7

  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing,
  # bi-directional text, and other internationalization issues.
  intl: ^0.17.0



  # XXTEA is a fast and secure encryption algorithm. This is a XXTEA library for Dart.
  xxtea: ^2.1.0

  # An helper to easily exposes a value using InheritedWidget without having to write one.
  sembast: ^3.1.0+2
  path_provider: ^2.0.2

  # Material Dialog
  material_dialog: ^1.0.0-nullsafety.1



  # Flogs, a powerful logging framework
  #  f_logs: ^1.2.2

  # MobX is a library for reactively managing the state of your applications. Use the power of
  # observables, actions, and reactions to supercharge your Dart and Flutter apps.
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0

  # An helper to easily exposes a value using InheritedWidget without having to write one.
  provider: ^5.0.0

  # String validation and sanitization for Dart. Dart 2-compatible version of validator
  validators: ^3.0.0

  # A flexible widget for user notification. Customize your text, button, duration, animations
  # and much more. For Android devs, it is made to replace Snackbars and Toasts.
  another_flushbar: ^1.10.23


  #  Animations Packages
  # Powerful package to create beautiful custom animations in no time.
  simple_animations: ^3.1.1
  flutter_staggered_animations: ^1.0.0
  animate_do: ^2.0.0
  lottie: ^1.0.1

  uuid: ^3.0.4

  modal_progress_hud_nsn: ^0.1.0-nullsafety-1


  cloud_firestore: ^2.3.0
  firebase_core: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5
  json_annotation: ^4.0.1
  json_serializable: ^4.1.3
  mobx_codegen: ^2.0.1+3
  test: ^1.16.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/
    - assets/animation/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
